/**
 * Cellex Design System
 * Generated by UI UX Pro Max skill — tailored for social commerce marketplace
 *
 * Design Pattern: Marketplace / Directory
 * Style: Minimalism & Swiss Style (clean, functional, high contrast)
 * Color Strategy: Trust colors + Category colors + Success green
 * Typography: Plus Jakarta Sans (headings) + Inter (body) — already in use
 *
 * Key UX Guidelines (from skill):
 * - Back button must preserve navigation history
 * - Sticky nav must not obscure content (add padding-top)
 * - Mobile keyboards: use inputmode attribute
 * - Skeleton loaders to avoid layout shifts
 * - cursor-pointer on all clickable elements
 * - Hover states with 150-300ms transitions
 * - Focus states visible for keyboard nav
 * - Responsive breakpoints: 375px, 768px, 1024px, 1440px
 */

export const DESIGN_TOKENS = {
  // Colors — Trust-building palette for Nigerian marketplace
  colors: {
    primary: '#111827',        // Black — CTAs, active states, text
    primaryHover: '#374151',   // Dark gray — hover states
    onPrimary: '#FFFFFF',      // White text on primary
    secondary: '#6B7280',      // Gray — secondary text
    accent: '#171717',         // Champagne gold — logo only
    background: '#FFFFFF',     // White — backgrounds, cards
    surface: '#F9FAFB',        // Light gray — input fields, cards
    border: '#E5E7EB',         // Light gray — borders
    success: '#16A34A',        // Green — success states, paid status
    warning: '#F59E0B',        // Amber — pending, escrow held
    destructive: '#DC2626',    // Red — errors, delete
    muted: '#9CA3AF',          // Light gray — muted text
  },

  // Typography — already using Plus Jakarta Sans + Sora
  typography: {
    heading: 'Plus Jakarta Sans, sans-serif',
    body: 'Plus Jakarta Sans, sans-serif',
    mono: 'Sora, monospace',
    sizes: {
      xs: '10px',
      sm: '12px',
      base: '14px',
      lg: '16px',
      xl: '20px',
      '2xl': '24px',
      '3xl': '30px',
    },
    weights: {
      normal: 400,
      medium: 500,
      semibold: 600,
      bold: 700,
      extrabold: 800,
    },
  },

  // Spacing — Swiss style: generous whitespace
  spacing: {
    xs: '4px',
    sm: '8px',
    md: '16px',
    lg: '24px',
    xl: '32px',
    '2xl': '48px',
    '3xl': '64px',
  },

  // Border radius
  radius: {
    sm: '8px',
    md: '12px',
    lg: '16px',
    xl: '20px',
    '2xl': '24px',
    full: '9999px',
  },

  // Transitions — 150-300ms per UX guidelines
  transitions: {
    fast: '150ms ease',
    base: '200ms ease',
    slow: '300ms ease',
  },

  // Shadows
  shadows: {
    sm: '0 1px 2px rgba(0,0,0,0.05)',
    md: '0 4px 6px rgba(0,0,0,0.07)',
    lg: '0 8px 24px rgba(0,0,0,0.12)',
    xl: '0 24px 80px rgba(0,0,0,0.25)',
  },

  // Breakpoints — per UX guidelines
  breakpoints: {
    mobile: '375px',
    tablet: '768px',
    desktop: '1024px',
    wide: '1440px',
  },

  // Z-index scale
  zIndex: {
    base: 0,
    dropdown: 10,
    sticky: 30,
    overlay: 50,
    modal: 100,
    toast: 200,
  },
} as const;

// CSS variables for global use
export const CSS_VARIABLES = `
:root {
  --color-primary: ${DESIGN_TOKENS.colors.primary};
  --color-primary-hover: ${DESIGN_TOKENS.colors.primaryHover};
  --color-on-primary: ${DESIGN_TOKENS.colors.onPrimary};
  --color-secondary: ${DESIGN_TOKENS.colors.secondary};
  --color-accent: ${DESIGN_TOKENS.colors.accent};
  --color-background: ${DESIGN_TOKENS.colors.background};
  --color-surface: ${DESIGN_TOKENS.colors.surface};
  --color-border: ${DESIGN_TOKENS.colors.border};
  --color-success: ${DESIGN_TOKENS.colors.success};
  --color-warning: ${DESIGN_TOKENS.colors.warning};
  --color-destructive: ${DESIGN_TOKENS.colors.destructive};
  --color-muted: ${DESIGN_TOKENS.colors.muted};

  --radius-sm: ${DESIGN_TOKENS.radius.sm};
  --radius-md: ${DESIGN_TOKENS.radius.md};
  --radius-lg: ${DESIGN_TOKENS.radius.lg};
  --radius-full: ${DESIGN_TOKENS.radius.full};

  --transition-fast: ${DESIGN_TOKENS.transitions.fast};
  --transition-base: ${DESIGN_TOKENS.transitions.base};

  --shadow-sm: ${DESIGN_TOKENS.shadows.sm};
  --shadow-md: ${DESIGN_TOKENS.shadows.md};
  --shadow-lg: ${DESIGN_TOKENS.shadows.lg};
}
`;

// UX Checklist (from skill's pre-delivery checklist)
export const UX_CHECKLIST = [
  'No emojis as icons (use SVG: Lucide)',
  'cursor-pointer on all clickable elements',
  'Hover states with smooth transitions (150-300ms)',
  'Light mode: text contrast 4.5:1 minimum',
  'Focus states visible for keyboard nav',
  'prefers-reduced-motion respected',
  'Responsive: 375px, 768px, 1024px, 1440px',
  'Skeleton loaders for async content',
  'inputmode attribute on mobile inputs',
  'Back button preserves navigation history',
];

// Animation snippets (from skill's GSAP recommendations)
export const ANIMATIONS = {
  scrollRevealSubtle: `
gsap.from(el, { opacity: 0, y: 12, duration: 0.35, ease: 'power1.out',
  scrollTrigger: { trigger: el, start: 'top 90%', toggleActions: 'play none none reverse' }
});
`,
  scrollRevealStagger: `
gsap.from(el.children, { opacity: 0, y: 24, duration: 0.5, stagger: 0.08, ease: 'power2.out',
  scrollTrigger: { trigger: el, start: 'top 85%' }
});
`,
};
